### ISSUE TITLE
Any hope of a python3 upgrade?

### ISSUE THREAD

**Issue by jkms** [micahg/plugin.video.snnow#18]
With NHL.tv shutting down, I can no longer use the NHL kodi app.  Hockey games are moving to Sportsnet Now, but this plugin is no longer compatible with the latest version of Kodi.

Would be awesome if I could use it on my Kodi box to watch my Canucks.

**Comment by micahg** [comment]
Hey, I wish I had the time to do it, but I don't.

I also don't have SNNow.

Sorry.
